layout_spectrum: 0
typography_spectrum: 0.05197133
color:
  saturation: 1
  lightness: 0.7741935
  brandStrength: 0.7114695
  rhythmicContrast: 0.04121864
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: KINGKONG IS A DOG
